# Web Scraping Assignment :4

## Flip Robo Technologies | Internship: 31

### Submitted By : Tamali Saha (tamali428@gmail.com)

In [1]:
#import necessary librabies for webscraping with selenium

import selenium
import pandas as pd
from selenium import webdriver
import warnings
warnings.filterwarnings("ignore")
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
from selenium.webdriver.common.by import By
import time
import requests
from time import sleep

### Q1. Scrape the details of most viewed videos on YouTube from Wikipedia. Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos. You need to find following details: A) Rank B) Name C) Artist D) Upload date E) Views

In [2]:
#First connect to the driver

driver= webdriver.Chrome(r"C:\Users\user\Downloads\chromedriver_win32\chromedriver.exe")

#open the page in automated chrome browser

driver.get("https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos")
time.sleep(2)

In [7]:
# Creating Empty list to store all the scrapped result
rank =[]
name =[]
artist =[]
upload_date=[]
views=[]

In [8]:
# Extracting Rank
try:
    rank_tags =driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[1]')
    for i in rank_tags:
        rank.append(i.text.split(".")[0])
except NoSuchElementException:
    rank.append('--')
except StaleElementReferenceException:
    rank.append('--')
    
# Extracting Name
try:
    name_tags =driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[2]')
    for i in name_tags:
        name.append(i.text.split("[")[0])
except NoSuchElementExceptionhElementException:
    name.append('--')
except StaleElementReferenceException:
    name.append('--')

# Extracting Artist
try:
    artist_tags =driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[3]")
    for i in artist_tags:
        artist.append(i.text)
except NoSuchElementExceptionhElementException:
    artist.append('--')
except StaleElementReferenceException:
    artist.append('--')
    
# Extracting Upload date 
try:
    upload_date_tags =driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[5]")
    for i in upload_date_tags:
        upload_date.append(i.text)
except NoSuchElementExceptionhElementException:
    upload_date.append('--')
except StaleElementReferenceException:
    upload_date.append('--')
    
    
# Extracting Views
try:
    views_tags=driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[4]")
    for i in views_tags :
        views.append(i.text)
except NoSuchElementExceptionhElementException:
    views.append('--')
except StaleElementReferenceException:
    views.append('--')

In [9]:
print(len(rank))
print(len(name))
print(len(artist))
print(len(upload_date))
print(len(views))

30
30
30
30
30

In [10]:
# Creating DataFrame for scrapped data

data_list= list(zip(rank, name,artist, upload_date,views ))

data= pd.DataFrame(data_list, 
    columns =['Rank', 'Name','Artist', 'Upload_date','Views '],
    index=pd.RangeIndex(start=1, stop=31, name='Sr. No.'))

#Print the required data

print ("Details of most viewed videos on YouTube from Wikipedia:\n")
data

Details of most viewed videos on YouTube from Wikipedia:

,Rank,Name,Artist,Upload_date,Views
Sr. No.,,,,,
1,1,"""Baby Shark Dance""",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",11.40
2,2,"""Despacito""",Luis Fonsi,"January 12, 2017",7.98
3,3,"""Johny Johny Yes Papa""",LooLoo Kids,"October 8, 2016",6.47
4,4,"""Shape of You""",Ed Sheeran,"January 30, 2017",5.81
5,5,"""See You Again""",Wiz Khalifa,"April 6, 2015",5.64
6,6,"""Bath Song""",Cocomelon – Nursery Rhymes,"May 2, 2018",5.63
7,7,"""Phonics Song with Two Words""",ChuChu TV,"March 6, 2014",4.90
8,8,"""Uptown Funk""",Mark Ronson,"November 19, 2014",4.70
9,9,"""Learning Colors – Colorful Eggs on a Farm""",Miroshka TV,"February 27, 2018",4.65
10,10,"""Gangnam Style""",Psy,"July 15, 2012",4.55
11,11,"""Masha and the Bear – Recipe for Disaster""",Get Movies,"January 31, 2012",4.51
12,12,"""Wheels on the Bus""",Cocomelon – Nursery Rhymes,"May 24, 2018",4.40
13,13,"""Dame Tu Cosita""",El Chombo,"April 5, 2018",4.07
14,14,"""Sugar""",Maroon 5,"January 14, 2015",3.76
15,15,"""Roar""",Katy Perry,"September 5, 2013",3.66
16,16,"""Counting Stars""",OneRepublic,"May 31, 2013",3.65
17,17,"""Sorry""",Justin Bieber,"October 22, 2015",3.59
18,18,"""Axel F""",Crazy Frog,"June 16, 2009",3.52
19,18,"""Thinking Out Loud""",Ed Sheeran,"October 7, 2014",3.50
20,20,"""Baa Baa Black Sheep""",Cocomelon – Nursery Rhymes,"June 25, 2018",3.38
21,21,"""Dark Horse""",Katy Perry,"February 20, 2014",3.35
22,22,"""Faded""",Alan Walker,"December 3, 2015",3.34
23,23,"""Girls Like You""",Maroon 5,"May 31, 2018",3.33
24,24,"""Let Her Go""",Passenger,"July 25, 2012",3.30
25,25,"""Bailando""",Enrique Iglesias,"April 11, 2014",3.27
26,26,"""Lean On""",Major Lazer,"March 22, 2015",3.26
27,27,"""Perfect""",Ed Sheeran,"November 9, 2017",3.26
28,28,"""Waka Waka (This Time for Africa)""",Shakira,"June 4, 2010",3.25
29,29,"""Shake It Off""",Taylor Swift,"August 18, 2014",3.21
30,30,"""Humpty the train on a fruits ride""",Kiddiestv Hindi – Nursery Rhymes & Kids Songs,"January 26, 2018",3.17

### Q2. 2. Scrape the details team India’s international fixtures from bcci.tv. Url = https://www.bcci.tv/. You need to find following details: A) Match title (I.e. 1st ODI) B) Series C) Place D) Date E) Time .                                                  
Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [19]:
#First connect to the driver

driver= webdriver.Chrome(r"C:\Users\user\Downloads\chromedriver_win32\chromedriver.exe")

#open the page in automated chrome browser

driver.get("https://www.bcci.tv/")
time.sleep(2)

In [20]:
# Opening fixtures

international =driver.find_element(By.XPATH,'//div[@class="collapse navbar-collapse"]/ul/li[2]/a')
try:
    international.click()
except ElementNotInteractableException:
    driver.get(international.get_attribute('href'))

In [21]:
# Creating empty list to store all the scrapped result
title = []
series = []
place = []
date = []
time = []
url=[]

In [22]:
# Extracting title
try:
    title_tags=driver.find_elements(By.XPATH,'//span[@class="ng-binding"]')
    for i in title_tags :
        title.append(i.text)
except StaleElementReferenceException:
    title.append('--')
title

['SOUTH AFRICA TOUR OF INDIA ODI SERIES 2022-23',
 'ASIA CUP WOMENS 2022',
 'ASIA CUP WOMENS 2022',
 'SOUTH AFRICA TOUR OF INDIA ODI SERIES 2022-23',
 'ASIA CUP WOMENS 2022',
 'SOUTH AFRICA TOUR OF INDIA ODI SERIES 2022-23']

In [23]:
# Extracting series
try:
    series_tags=driver.find_elements(By.XPATH,'//span[@class="matchOrderText ng-binding ng-scope"]')
    for i in series_tags :
        series.append(i.text.split("-")[0])
except StaleElementReferenceException:
    series.append('--')
series

['1st ODI ', '4th T20I ', '5th T20I ', '2nd ODI ', '6th T20I ', '3rd ODI ']

In [24]:
# Extracting place
try:
    place_tags=driver.find_elements(By.XPATH,'//span[@class="ng-binding ng-scope"]')
    for i in place_tags :
        place.append(i.text.replace(','," "))
except StaleElementReferenceException:
    place.append('--')
place

['Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium ',
 'Sylhet International Cricket Stadium ',
 'Sylhet International Cricket Stadium ',
 'JSCA International Stadium Complex ',
 'Sylhet International Cricket Stadium ',
 'Arun Jaitley Stadium ']

In [25]:
# Extracting date
try:
    date_tags=driver.find_elements(By.XPATH,'//h5[@class="ng-binding"]')
    for i in date_tags :
        date.append(i.text)
except StaleElementReferenceException:
    date.append('--')
date

['6 OCT 2022',
 '7 OCT 2022',
 '8 OCT 2022',
 '9 OCT 2022',
 '10 OCT 2022',
 '11 OCT 2022']

In [26]:
# Extracting time
try:
    time_tags=driver.find_elements(By.XPATH,'//h5[@class="text-right ng-binding"]')
    for i in time_tags :
        time.append(i.text)
except StaleElementReferenceException:
    time.append('--')
time

['1:30 PM IST',
 '1:00 PM IST',
 '1:00 PM IST',
 '1:30 PM IST',
 '1:00 PM IST',
 '1:30 PM IST']

In [27]:
# Extracting url
url_tags=driver.find_elements(By.XPATH,'//a[@class="match-center-btn ng-scope"]')
for i in url_tags :
    url.append(i.get_attribute('href'))

In [28]:
url

['https://www.bcci.tv/events/82/south-africa-tour-of-india-odi-series-2022-23/match/642/1st-odi',
 'https://www.bcci.tv/events/86/asia-cup-womens-2022/match/682/4th-t20i',
 'https://www.bcci.tv/events/86/asia-cup-womens-2022/match/684/5th-t20i',
 'https://www.bcci.tv/events/82/south-africa-tour-of-india-odi-series-2022-23/match/643/2nd-odi',
 'https://www.bcci.tv/events/86/asia-cup-womens-2022/match/683/6th-t20i',
 'https://www.bcci.tv/events/82/south-africa-tour-of-india-odi-series-2022-23/match/644/3rd-odi']

In [30]:
# Creating DataFrame for scrapped data

data_list= list(zip(title,series,place, date,time,url ))

data= pd.DataFrame(data_list, 
    columns =['Title', 'Series','Place', 'Date','Time ', 'URL'])

#Print the required data

print ("Details team India’s international fixtures from bcci.tv.:\n")
data

Details team India’s international fixtures from bcci.tv.:

,Title,Series,Place,Date,Time,URL
0,SOUTH AFRICA TOUR OF INDIA ODI SERIES 2022-23,1st ODI,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,6 OCT 2022,1:30 PM IST,https://www.bcci.tv/events/82/south-africa-tou...
1,ASIA CUP WOMENS 2022,4th T20I,Sylhet International Cricket Stadium,7 OCT 2022,1:00 PM IST,https://www.bcci.tv/events/86/asia-cup-womens-...
2,ASIA CUP WOMENS 2022,5th T20I,Sylhet International Cricket Stadium,8 OCT 2022,1:00 PM IST,https://www.bcci.tv/events/86/asia-cup-womens-...
3,SOUTH AFRICA TOUR OF INDIA ODI SERIES 2022-23,2nd ODI,JSCA International Stadium Complex,9 OCT 2022,1:30 PM IST,https://www.bcci.tv/events/82/south-africa-tou...
4,ASIA CUP WOMENS 2022,6th T20I,Sylhet International Cricket Stadium,10 OCT 2022,1:00 PM IST,https://www.bcci.tv/events/86/asia-cup-womens-...
5,SOUTH AFRICA TOUR OF INDIA ODI SERIES 2022-23,3rd ODI,Arun Jaitley Stadium,11 OCT 2022,1:30 PM IST,https://www.bcci.tv/events/82/south-africa-tou...

### Q3. Scrape the details of selenium exception from guru99.com. Url = https://www.guru99.com/ You need to find following details: A) Name B) Description
Note: - From guru99 home page you have to reach to selenium exception handling page through code

In [31]:
#First connect to the driver

driver= webdriver.Chrome(r"C:\Users\user\Downloads\chromedriver_win32\chromedriver.exe")

#open the page in automated chrome browser

driver.get("https://www.guru99.com/")
time.sleep(2)

In [32]:
# Selecting Selenium option

selenium=driver.find_element(By.XPATH,'//div[@class="featured-box cloumnsize1"]/ul[1]/li[3]/a')
try:
    selenium.click()
except ElementNotInteractableException:
    driver.get(selenium.get_attribute('href'))

In [33]:
# Selecting Selenium exception

exceptation =driver.find_element(By.XPATH,'//*[@id="post-193"]/div/div/table[5]/tbody/tr[34]/td[1]/a')
try:
    exceptation.click()
    time.sleep(2)
except ElementNotInteractableException:
    driver.get(exceptation.get_attribute('href'))
    time.sleep(2)

In [90]:
# Creating Empty list to store all the scrapped result
name =[]
description=[]

In [91]:
# Extracting name and description of exception
all_info=[]
try:
    all_tags =driver.find_elements(By.XPATH,'//div[@class="entry-content single-content"]/p')
    for i in all_tags:
        all_info.append(i.text.split(":"))
except NoSuchElementException:
    all_info.append('--')
all_info1= all_info[:41]

jj=[]
for i in all_info1:
    for j in i:
        jj.append(j)
        

for i in range(0, len(jj)):
    if i % 2 ==0:
        name.append(jj[i])

for i in range(0, len(jj)):
    if i % 2 ==1:
        description.append(jj[i])

In [94]:
print(len(name))
print(len(description))

41
41

In [95]:
# Creating DataFrame for scrapped data

data_list= list(zip(name,description ))

data= pd.DataFrame(data_list, 
    columns =['Name','Description'],
    index=pd.RangeIndex(start=1, stop=42, name='Sr. No.'))

#Print the required data

print ("Details of selenium exception from guru99.com:\n")
data

Details of selenium exception from guru99.com:

,Name,Description
Sr. No.,,
1,1. ElementNotVisibleException,This type of Selenium exception occurs when a...
2,2. ElementNotSelectableException,This Selenium exception occurs when an elemen...
3,3. NoSuchElementException,This Exception occurs if an element could not...
4,4. NoSuchFrameException,This Exception occurs if the frame target to ...
5,5. NoAlertPresentException,This Exception occurs when you switch to no p...
6,6. NoSuchWindowException,This Exception occurs if the window target to...
7,7. StaleElementReferenceException,This Selenium exception occurs happens when t...
8,8. SessionNotFoundException,The WebDriver is acting after you quit the br...
9,9. TimeoutException,Thrown when there is not enough time for a co...
10,10. WebDriverException,This Exception takes place when the WebDriver...
11,11. ConnectionClosedException,This type of Exception takes place when there...
12,12. ElementClickInterceptedException,The command may not be completed as the eleme...
13,13. ElementNotInteractableException,This Selenium exception is thrown when any el...
14,14. ErrorInResponseException,This happens while interacting with the Firef...
15,15. ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if...
16,16. ImeActivationFailedException,This expectation will occur when IME engine a...
17,17. ImeNotAvailableException,It takes place when IME support is unavailable.
18,18. InsecureCertificateException,Navigation made the user agent to hit a certi...
19,19. InvalidArgumentException,It occurs when an argument does not belong to...
20,20. InvalidCookieDomainException,This happens when you try to add a cookie und...
21,21. InvalidCoordinatesException,This type of Exception matches an interacting...
22,22. InvalidElementStateException,It occurs when command can’t be finished when...
23,23. InvalidSessionIdException,This Exception took place when the given sess...
24,24. InvalidSwitchToTargetException,This occurs when the frame or window target t...
25,25. JavascriptException,This issue occurs while executing JavaScript ...
26,26. JsonException,It occurs when you afford to get the session ...
27,27. NoSuchAttributeException,This kind of Exception occurs when the attrib...
28,28. MoveTargetOutOfBoundsException,It takes place if the target provided to the ...
29,29. NoSuchContextException,ContextAware does mobile device testing.
30,30. NoSuchCookieException,This Exception occurs when no cookie matching...
31,31. NotFoundException,This Exception is a subclass of WebDriverExce...
32,32. RemoteDriverServerException,This Selenium exception is thrown when the se...
33,33. ScreenshotException,It is not possible to capture a screen.
34,34. SessionNotCreatedException,It happens when a new session could not be su...
35,35. UnableToSetCookieException,This occurs if a driver is unable to set a co...
36,36. UnexpectedTagNameException,Happens if a support class did not get a web ...
37,37. UnhandledAlertException,This expectation occurs when there is an aler...
38,38. UnexpectedAlertPresentException,It occurs when there is the appearance of an ...
39,39. UnknownMethodException,This Exception happens when the requested com...
40,40. UnreachableBrowserException,This Exception occurs only when the browser i...
41,41. UnsupportedCommandException,This occurs when remote WebDriver doesn’t sen...

### Q4.  Scrape the details of State-wise GDP of India from statisticstime.com. Url = http://statisticstimes.com/ You have to find following details: A) Rank B) State C) GSDP(19-20)  D) GSDP (18-19) E) Share  (18-19) F) GDP (billion)
Note: - From statisticstimes home page you have to reach to economy page through code

In [104]:
#First connect to the driver

driver= webdriver.Chrome(r"C:\Users\user\Downloads\chromedriver_win32\chromedriver.exe")

#open the page in automated chrome browser

driver.get("http://statisticstimes.com/")
time.sleep(2)

In [105]:
# Clicking on ecomony tab

India=driver.find_element(By.XPATH,'//div[@class="dropdown"][2]/button')
try:
    India.click()
except ElementNotInteractableException:
    driver.get(India.get_attribute('href'))  
time.sleep(2)

In [106]:
# Clicking on India from economy tab
state = driver.find_element(By.XPATH,'/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]')
driver.get(state.get_attribute('href'))
time.sleep(2)

In [111]:
# Clicking on GDP of Indian state

state = driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[2]/ul/li[1]/a')
driver.get(state.get_attribute('href'))
time.sleep(2)

In [133]:
# Creating empty lists to store all the scrapped result
rank =[]
state =[]
gsdp_19_20=[]
gsdp_18_19 =[]
share_18_19 =[]
GDP =[]

In [134]:
# Extracting Rank 
try:
    rank_tags =driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[1]')
    for i in rank_tags :
        rank.append(i.text)
except NoSuchElementException:
    rank.append('NA')
    
# Extracting state name
try:
    state_tags =driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[2]')
    for i in state_tags:
        state.append(i.text)
except NoSuchElementException:
    state.append('NA')
    
# Extracting GDSP 19-20
try:
    gsdp_19_20_tags =driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[3]')
    for i in gsdp_19_20_tags:
        gsdp_19_20.append(i.text)
except NoSuchElementException:
    gsdp_19_20.append('NA')
    
# Extracting GDSP 18-19
try:
    gsdp_18_19_tags =driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[4]')
    for i in gsdp_18_19_tags:
        gsdp_18_19.append(i.text)
except NoSuchElementException:
    gsdp_18_19.append('NA')
    
# Extracting Share 18_19
try:
    share_18_19_tags =driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[5]')
    for i in share_18_19_tags:
        share_18_19.append(i.text)
except NoSuchElementException:
    share_18_19.append('NA')
    
# Extracting GDP
try:
    GDP_tags =driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[6]')
    for i in GDP_tags:
        GDP.append(i.text)
except NoSuchElementException:
    GDP.append('NA')

In [135]:
print(len(rank))
print(len(state))
print(len(gsdp_19_20))
print(len(gsdp_18_19))
print(len(share_18_19))
print(len(GDP))

33
33
33
33
33
33

In [139]:
# Creating DataFrame for scrapped data

data_list= list(zip(rank, state,gsdp_19_20, gsdp_18_19,share_18_19 , GDP))

data= pd.DataFrame(data_list, 
    columns =['Rank', 'State', 'GSDP_19_20','GSDP_18_19','Share_18_19' , 'GDP'],
                index=pd.RangeIndex(start=1, stop=34, name='Sr. No.'))

#Print the required data

print ("Details of State-wise GDP of India from statisticstime.com:\n")
data

Details of State-wise GDP of India from statisticstime.com:

,Rank,State,GSDP_19_20,GSDP_18_19,Share_18_19,GDP
Sr. No.,,,,,,
1,1,Maharashtra,-,"2,632,792",13.94%,399.921
2,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
3,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
4,4,Gujarat,-,"1,502,899",7.96%,228.290
5,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
6,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
7,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
8,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
9,9,Telangana,"969,604","861,031",4.56%,130.791
10,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
11,11,Kerala,-,"781,653",4.14%,118.733
12,12,Delhi,"856,112","774,870",4.10%,117.703
13,13,Haryana,"831,610","734,163",3.89%,111.519
14,14,Bihar,"611,804","530,363",2.81%,80.562
15,15,Punjab,"574,760","526,376",2.79%,79.957
16,16,Odisha,"521,275","487,805",2.58%,74.098
17,17,Assam,-,"315,881",1.67%,47.982
18,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
19,19,Jharkhand,"328,598","297,204",1.57%,45.145
20,20,Uttarakhand,-,"245,895",1.30%,37.351
21,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
22,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
23,23,Goa,"80,449","73,170",0.39%,11.115
24,24,Tripura,"55,984","49,845",0.26%,7.571
25,25,Chandigarh,-,"42,114",0.22%,6.397
26,26,Puducherry,"38,253","34,433",0.18%,5.230
27,27,Meghalaya,"36,572","33,481",0.18%,5.086
28,28,Sikkim,"32,496","28,723",0.15%,4.363
29,29,Manipur,"31,790","27,870",0.15%,4.233
30,30,Nagaland,-,"27,283",0.14%,4.144
31,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
32,32,Mizoram,"26,503","22,287",0.12%,3.385
33,33,Andaman & Nicobar Islands,-,-,-,-

### Q5. Scrape the details of trending repositories on Github.com. Url = https://github.com/You have to find the following details:A) Repository title B) Repository description C) Contributors count D) Language used
Note: - From the home page you have to click on the trending option from Explore menu through code.

In [180]:
#First connect to the driver

driver= webdriver.Chrome(r"C:\Users\user\Downloads\chromedriver_win32\chromedriver.exe")

#open the page in automated chrome browser

driver.get("https://github.com/You")
time.sleep(2)

In [181]:
# Clicking on button tab

button =driver.find_element(By.XPATH,'/html/body/div[1]/header/div/div[2]/div/nav/ul/li[3]/div/ul[3]/li[3]/a')
driver.get(button.get_attribute('href'))
time.sleep(2)

In [182]:
# Creating Empty list for Scraping Data
title=[]
description=[]
count =[]
language =[]
url=[]

In [183]:
# Extracting Share 18_19
try:
    title_tags =driver.find_elements(By.XPATH,'//h1[@class="h3 lh-condensed"]')
    for i in title_tags:
        title.append(i.text)
except NoSuchElementException:
    title.append('NA')

In [184]:
len(title)

25

In [185]:
# Extracting URL

try:
    url_tags =driver.find_elements(By.XPATH,'//h1[@class="h3 lh-condensed"]/a')
    for i in url_tags:
        url.append(i.get_attribute("href"))
except NoSuchElementException:
    url.append('NA')
len(url)

25

In [186]:
for i in url:
    driver.get(i)
    time.sleep(1)
    
    try:
        description_tags=driver.find_element(By.XPATH,'/html/body/div[4]/div/main/turbo-frame/div/div/div/div[3]/div[2]/div/div[1]/div/p')
        description.append(description_tags.text)
    except NoSuchElementException:
        description.append('NA')

In [187]:
len(description)

25

In [188]:
for i in url:
    driver.get(i)
    time.sleep(1)
    
    try:
        count_tags=driver.find_element(By.XPATH, "//h2[@class='h4 mb-3']/a[contains(text(),'Contributors')]/span")
        count.append(count_tags.text)
    except NoSuchElementException:
        count.append('NA')

In [189]:
len(count)

25

In [190]:
for i in url:
    driver.get(i)
    time.sleep(1)

    # Scraping Language
    L =[]
    try:
        language_tag =driver.find_elements(By.XPATH,"//li[@class='d-inline']//a//span[1]")
        if language_tag:
            for j in language_tag:
                L.append(j.text)
        else:
            L.append('NA')
        language.append(L)
    except NoSuchElementException:
        language.append('NA')

In [191]:
len(language)

25

In [198]:
# Creating DataFrame for scrapped data

data_list= list(zip(title,description,count,language,url ))

data= pd.DataFrame(data_list, 
    columns =['Title', 'Description', 'Count','Language','URL'],
                  index=pd.RangeIndex(start=1, stop=26, name='Sr. No.'))

#Print the required data

print ("Details of trending repositories on Github.com:\n")
data

Details of trending repositories on Github.com:

,Title,Description,Count,Language,URL
Sr. No.,,,,,
1,total-typescript / beginners-typescript-tutorial,An interactive TypeScript tutorial for beginners,12,"[TypeScript, JavaScript]",https://github.com/total-typescript/beginners-...
2,penpot / penpot,Penpot - The Open-Source design & prototyping ...,78,"[Clojure, SCSS, JavaScript, HTML, Shell, Docke...",https://github.com/penpot/penpot
3,cypress-io / cypress,"Fast, easy and reliable testing for anything t...",395,"[JavaScript, TypeScript, Vue, HTML, SCSS, CSS]",https://github.com/cypress-io/cypress
4,google / googletest,GoogleTest - Google Testing and Mocking Framework,369,"[C++, Python, CMake]",https://github.com/google/googletest
5,lucidrains / make-a-video-pytorch,"Implementation of Make-A-Video, new SOTA text ...",NA,[Python],https://github.com/lucidrains/make-a-video-pyt...
6,NielsRogge / Transformers-Tutorials,This repository contains demos I made with the...,3,[Jupyter Notebook],https://github.com/NielsRogge/Transformers-Tut...
7,nv-tlabs / GET3D,NA,NA,"[Python, Cuda, C++]",https://github.com/nv-tlabs/GET3D
8,inspiradanacomputacao / tecnologistas-contra-b...,Manifesto de Pessoas Tecnologistas contra Bols...,126,[NA],https://github.com/inspiradanacomputacao/tecno...
9,Ildaron / Laser_control,"Open-Source Laser for control mosquito, weed, ...",NA,"[Python, Makefile]",https://github.com/Ildaron/Laser_control
10,developedbyed / react-portofolio-with-tailwind,NA,NA,"[JavaScript, CSS]",https://github.com/developedbyed/react-portofo...
11,Nickyie / Cybersecurity-Resources,A Library of various cybersecurity resources,2,[NA],https://github.com/Nickyie/Cybersecurity-Resou...
12,isaced / V2exOS,一个用 SwiftUI 编写的 V2ex macOS 客户端（Beta）,2,[Swift],https://github.com/isaced/V2exOS
13,IceWhaleTech / CasaOS,"CasaOS - A simple, easy-to-use, elegant open-s...",9,"[Go, Shell, Makefile]",https://github.com/IceWhaleTech/CasaOS
14,Asabeneh / 30-Days-Of-Python,30 days of Python programming challenge is a s...,7,"[Python, CSS, HTML]",https://github.com/Asabeneh/30-Days-Of-Python
15,google / latexify_py,Generates LaTeX math description from Python f...,6,[Python],https://github.com/google/latexify_py
16,denoland / deno,A modern runtime for JavaScript and TypeScript.,747,"[Rust, JavaScript, TypeScript]",https://github.com/denoland/deno
17,phoenixframework / phoenix,Peace of mind from prototype to production,"1,075","[Elixir, JavaScript, HTML, CSS, Euphoria, Eart...",https://github.com/phoenixframework/phoenix
18,microsoft / Web-Dev-For-Beginners,"24 Lessons, 12 Weeks, Get Started as a Web Dev...",149,"[JavaScript, HTML, CSS, Vue]",https://github.com/microsoft/Web-Dev-For-Begin...
19,CompVis / stable-diffusion,A latent text-to-image diffusion model,7,"[Jupyter Notebook, Python, Shell]",https://github.com/CompVis/stable-diffusion
20,fireship-io / fireship.io,Build and ship your app faster https://fireshi...,198,"[Svelte, HTML, TypeScript, SCSS, JavaScript]",https://github.com/fireship-io/fireship.io
21,lidangzzz / How-to-run,立党老师的润学（零基础转码/移民/留学/海外创业/永居）笔记,NA,[NA],https://github.com/lidangzzz/How-to-run
22,novuhq / novu,🚀 The open-source notifications infrastructure...,102,"[TypeScript, JavaScript, HTML, Handlebars, EJS...",https://github.com/novuhq/novu
23,docker / awesome-compose,Awesome Docker Compose samples,60,"[HTML, Dockerfile, TypeScript, Java, Python, C#]",https://github.com/docker/awesome-compose
24,Asabeneh / 30-Days-Of-JavaScript,30 days of JavaScript programming challenge is...,31,"[JavaScript, HTML]",https://github.com/Asabeneh/30-Days-Of-JavaScript
25,dosisod / refurb,A tool for refurbishing and modernizing Python...,3,[Python],https://github.com/dosisod/refurb

### Q 6. Scrape the details of top 100 songs on billiboard.com. Url = https:/www.billboard.com/ You have to find the following details: A) Song name B) Artist name C) Last week rank D) Peak rank E) Weeks on board
Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [2]:
#First connect to the driver

driver= webdriver.Chrome(r"C:\Users\user\Downloads\chromedriver_win32\chromedriver.exe")

#open the page in automated chrome browser

driver.get(" https:/www.billboard.com/")
time.sleep(2)

In [3]:
# Clicking on button tab

button =driver.find_element(By.XPATH,'/html/body/div[3]/header/div/div[2]/div/div/div[2]/div[2]/div/div/nav/ul/li[1]/a')
driver.get(button.get_attribute('href'))
time.sleep(2)

In [4]:
# Clicking on hot100 tab

hot100 =driver.find_element(By.XPATH,'/html/body/div[3]/header/div/div[3]/div/nav/ul/li[1]/a')
driver.get(hot100.get_attribute('href'))
time.sleep(2)

In [20]:
# Creating Empty List for scrapped datas

name =[]
artist =[]
rank=[]
peak_rank =[]
weeks =[]
all_info=[]

In [21]:
# Scraping Song Name
try:
    song_tags =driver.find_elements(By.XPATH,'//ul[@class="lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max"]/li/h3')
    for i in song_tags:
        name.append(i.text)
except NoSuchElementException:
    name.append('NA')

In [23]:
len(name)

100

In [24]:
all_info=[]
try:
    all_tags =driver.find_elements(By.XPATH,'//ul[@class="lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max"]/li/span')
    for i in all_tags:
        all_info.append(i.text)
except NoSuchElementException:
    all_info.append('NA')

In [26]:
# Scraping artist
artist= all_info[0:401:4]
len(artist)

100

In [28]:
# Scraping rank
rank= all_info[1:401:4]
len(rank)

100

In [30]:
# Scraping rank
peak_rank= all_info[2:401:4]
len(peak_rank)

100

In [31]:
# Scraping weeks
weeks= all_info[3:401:4]
len(weeks)

100

In [35]:
# Creating DataFrame for scrapped data

data_list= list(zip(name,artist,rank,peak_rank,weeks ))

data= pd.DataFrame(data_list, 
    columns =['Song_name', 'Artist_name', 'Last_week_rank','Peak_rank','Weeks on board'],
                  index=pd.RangeIndex(start=1, stop=101, name='This_week_rank'))

#Print the required data

print ("Details of top 100 songs on billiboard.com.:\n")
data

Details of top 100 songs on billiboard.com.:

,Song_name,Artist_name,Last_week_rank,Peak_rank,Weeks on board
This_week_rank,,,,,
1,As It Was,Harry Styles,1,1,25
2,Bad Habit,Steve Lacy,2,2,12
3,I Like You (A Happier Song),Post Malone Featuring Doja Cat,5,3,16
4,Sunroof,Nicky Youre & dazy,4,4,17
5,Super Freaky Girl,Nicki Minaj,3,1,6
...,...,...,...,...,...
96,Thought You Should Know,Morgan Wallen,98,12,20
97,Where It Ends,Bailey Zimmerman,93,32,5
98,Backstage Passes,EST Gee Featuring Jack Harlow,-,98,1
99,Snap,Rosa Linn,97,93,4
100,Beat The Odds,Lil Tjay,91,36,4

### Q7.Scrape the details of Data science recruiters from naukri.com. Url = https://www.naukri.com/. You have to find the following details: A) Name B) Designation C) Company D) Skills they hire for E) Location
Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and
click on search. All this should be done through code

In [68]:
#First connect to the driver

driver= webdriver.Chrome(r"chromedriver.exe")

#open the page in automated chrome browser

driver.get("https://www.naukri.com/data-science-recruiters")

In [69]:
# Creating Empty List for scrapped datas
name=[] 
designation=[] 
company=[] 
skills=[]
url=[]

In [70]:
# Scraping name
try:
    name_tags =driver.find_elements(By.XPATH,'//span[@class="fl ellipsis"]')
    for i in name_tags:
        name.append(i.text)
except NoSuchElementException:
    name.append('NA')

In [71]:
len(name)

50

In [72]:
# Scraping designation
try:
    des_tags =driver.find_elements(By.XPATH,'//span[@class="ellipsis clr"]')
    for i in des_tags:
        designation.append(i.text)
except NoSuchElementException:
    designation.append('NA')

In [73]:
len(designation)

50

In [74]:
# Scraping company
comp=[]
try:
    com_tags =driver.find_elements(By.XPATH,'//a[@class="ellipsis"]')
    for i in com_tags:
        comp.append(i.text)
except NoSuchElementException:
    comp.append('NA')
    
for i in range(0, len(comp)):
    if i %2==1:
        company.append(comp[i])

In [75]:
len(company)

50

In [76]:
# Scraping skills
try:
    skills_tags =driver.find_elements(By.XPATH,'//div[@class="hireSec highlightable"]')
    for i in skills_tags:
        skills.append(i.text)
except NoSuchElementException:
    skills.append('NA')

In [77]:
len(skills)

50

In [78]:
# Scraping url
try:
    url_tags =driver.find_elements(By.XPATH,'//div[@class="recImg mid_pImg_Silht"]/a')
    for i in url_tags:
        url.append(i.get_attribute("href"))
except NoSuchElementException:
    url.append('NA')

In [79]:
len(url)

50

In [80]:
# Creating DataFrame for scrapped data

data_list= list(zip(name,designation,company,skills,url))

data= pd.DataFrame(data_list, 
    columns =['Name', 'Designation', 'Company','Skills','URL'],
                  index=pd.RangeIndex(start=1, stop=51, name='Sr No'))

#Print the required data

print ("Details of Data science recruiters from naukri.com:\n")
data

Details of Data science recruiters from naukri.com:

,Name,Designation,Company,Skills,URL
Sr No,,,,,
1,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",https://www.naukri.com/recruiters/aakashharit-...
2,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration...",https://www.naukri.com/recruiters/shravankumar...
3,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",https://www.naukri.com/recruiters/marsiantech?...
4,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",https://www.naukri.com/recruiters/anikagrawal-...
5,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architec...",https://www.naukri.com/recruiters/LXP-DATASCIE...
6,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana...",https://www.naukri.com/recruiters/abhishekyada...
7,Institute for Financial Management and Resear,Programme Manager,IFMR,Data Science,https://www.naukri.com/recruiters/menakav-3213...
8,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu...",https://www.naukri.com/recruiters/techvantage?...
9,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development, Pres...",https://www.naukri.com/recruiters/asiflucknowi...
10,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Software Development, It Sales, Account Manage...",https://www.naukri.com/recruiters/instafinanci...
11,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Social Media, digital media maketing, seo, smm...",https://www.naukri.com/recruiters/maheshbabuch...
12,Priyanka Akiri,HR Manager,Infinitive Software Solutions,"Oracle Dba, Data Science, Data Warehousing, ET...",https://www.naukri.com/recruiters/priyankaakir...
13,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa, Ui/ux, Java Developer, Java Architect, C++...",https://www.naukri.com/recruiters/kalpana-2078...
14,Mubarak,Company HR,MoneyTap,"Business Intelligence, Data Warehousing, Data ...",https://www.naukri.com/recruiters/mubarak-2905...
15,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,"Office Administration, Hr Administration, tele...",https://www.naukri.com/recruiters/quantmagnum?...
16,Vaishnavi Kudalkar,HR Executive,Codeachive learning,"Data Science, Python, Data Analytics",https://www.naukri.com/recruiters/vaishnavikud...
17,Kapil Devang,HR Manager,BISP Solutions,"Big Data, Hadoop, Data Analytics, Data Science",https://www.naukri.com/recruiters/kapildevang-...
18,Sakshi Chhikara,Assistant Manager HR,BIZ INFOTECNO PRIVATE LIMITED,"React.js, Data Science, Java, Front End, Busin...",https://www.naukri.com/recruiters/sakshichhika...
19,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,"Qlikview, Qlik Sense, Microsoft Azure, Power B...",https://www.naukri.com/recruiters/ruchidhote?x...
20,Manisha Yadav,HR Executive,Easi Tax,"Telecalling, Client Interaction, Marketing, Re...",https://www.naukri.com/recruiters/manishayadav...
21,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Data Science,https://www.naukri.com/recruiters/riyarajesh-4...
22,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,"Corporate Sales, Software Development, Softwar...",https://www.naukri.com/recruiters/rashmibhatta...
23,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics, Data Science, Machine Learning...",https://www.naukri.com/recruiters/faizankareem...
24,Rithika dadwal,HR Recruiter,Affine Analytics,"Data Science, Machine Learning, Python, R, Dee...",https://www.naukri.com/recruiters/rithikadadwa...
25,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"Big Data, Data Science, Artificial Intelligenc...",https://www.naukri.com/recruiters/ankitshah-21...
26,Shaun Rao,Manager Human Resources,Exela Technologies,"Java, Net, Angularjs, Hr, Infrastructure, Mana...",https://www.naukri.com/recruiters/shaunrao-302...
27,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Data Science, Artificial Intelligence, Machine...",https://www.naukri.com/recruiters/azaharshaikh...
28,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,"Software Architecture, Vp Engineering, Product...",https://www.naukri.com/recruiters/manas-315903...
29,kumar,Proprietor,trainin,"Data Science, Hadoop, Rpas, Devops, Python, Aw...",https://www.naukri.com/recruiters/kumar-337889...
30,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing, Machine Learning, Neural Ne...",https://www.naukri.com/recruiters/sunilvedula-...
31,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,"Web Technologies, Project Management, Software...",https://www.naukri.com/recruiters/rajatkumar-3...
32,Dhruv Dev Dubey,Company Recruitment Head,Confidential,"Server Administartion, Verilog, Vhdl, Digital ...",https://www.naukri.com/recruiters/dhruvdevdube...
33,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading...",https://www.naukri.com/recruiters/jayanthn-308...
34,Avodha,Business Development Associate,Nikitha Palaparthi,"Ethical Hacking, Security Operations Center, S...",https://www.naukri.com/recruiters/nikithapalap...
35,Priya Khare,Senior Manager,Independent Consultant,"Data Science, Artificial Intelligence, analyti...",https://www.naukri.com/recruiters/priyakhare-4...
36,Amit Sharma,Consultant,ASCO consulting,"Machine Learning, Artificial Intelligence, Dat...",https://www.naukri.com/recruiters/amitsharma-4...
37,Kanan,senior technology instructor,NY INST,"C, C++, Artificial Intelligence, Python, Php, ...",https://www.naukri.com/recruiters/deepali002g?...
38,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,"Relationship Management, Retail Sales, Private...",https://www.naukri.com/recruiters/shashikantch...
39,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Data Science, Software Engineering",https://www.naukri.com/recruiters/brad-4068508...
40,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Data Science, Big Data Analytics, Digital Mark...",https://www.naukri.com/recruiters/rutujapawar?...
41,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,"Data Science, Recruitment, Salary",https://www.naukri.com/recruiters/madhusudhans...
42,Ankit Sinha,Head Analytics,Suntech Global,"B.Tech, Tableau, Statistics, R, Analytics, Tim...",https://www.naukri.com/recruiters/ankitsinha-3...
43,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Software Development, Business Intelligence, B...",https://www.naukri.com/recruiters/gauravchouha...
44,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science, Node.js, Angularjs",https://www.naukri.com/recruiters/impel?xid=16...
45,Ashwini,Director Global Delivery,MRP Advisers,"Data Science, Media Marketing, Resource Planni...",https://www.naukri.com/recruiters/ashwini-3434...
46,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,"Data Analysis, Learning, Data Science, Compute...",https://www.naukri.com/recruiters/balajikolli-...
47,Rajani Nagaraj,HR Manager,WildJasmine,"Java, Hadoop, R, Machine Learning, Spark, Flum...",https://www.naukri.com/recruiters/rajaninagara...
48,ROHIT Kumar,Architect,LNT Private Limited,"Software Development, Core Java, Unit Testing,...",https://www.naukri.com/recruiters/rohitkumar-3...
49,Amir Chowdhury,Managing Partner,Granular.ai,"Machine Learning, Data Science, Product Manage...",https://www.naukri.com/recruiters/amirchowdhur...
50,Daniel Vaz,Partner,Aquis Search,"c++, Core Java, kdb, high frequency trading, h...",https://www.naukri.com/recruiters/danielvaz?xi...

### Q8. Scrape the details of Highest selling novels. Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/ You have to find the following details: A) Book name B) Author name C) Volumes sold D) Publisher E) Genre

In [38]:
#First connect to the driver

driver= webdriver.Chrome(r"C:\Users\user\Downloads\chromedriver_win32\chromedriver.exe")

#open the page in automated chrome browser

driver.get("  https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/")
time.sleep(2)

In [39]:
# Creating Empty Lists for scrapped data

book =[]
author =[]
volumes_sold =[]
publisher =[]
genre =[]

In [40]:
# Scraping Book name
try:
    book_tags =driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[2]')
    for i in book_tags:
        book.append(i.text)
except NoSuchElementException:
    book.append('NA')

In [42]:
len(book)

100

In [43]:
# Scraping Book author's
try:
    author_tags =driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[3]')
    for i in author_tags:
        author.append(i.text)
except NoSuchElementException:
    author.append('NA')

In [45]:
len(author)

100

In [47]:
# Scraping Volumes sold
try:
    volumes_sold_tags =driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[4]')
    for i in volumes_sold_tags :
        volumes_sold.append(i.text)
except NoSuchElementException:
    volumes_sold.append('NA')

In [49]:
len(volumes_sold)

100

In [50]:
# Scraping publisher
try:
    publisher_tags =driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[5]')
    for i in publisher_tags :
        publisher.append(i.text)
except NoSuchElementException:
    publisher.append('NA')

In [52]:
len(publisher)

100

In [53]:
# Scraping genre
try:
    genre_tags =driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[6]')
    for i in genre_tags :
        genre.append(i.text)
except NoSuchElementException:
    genre.append('NA')

In [55]:
len(genre)

100

In [56]:
# Creating DataFrame for scrapped data

data_list= list(zip(book,author,volumes_sold,publisher,genre ))

data= pd.DataFrame(data_list, 
    columns =['Book', 'Book_ Author', 'Volumes_Sold','Publisher','Genre'],
                  index=pd.RangeIndex(start=1, stop=101, name='Rank'))

#Print the required data

print ("Details of Highest selling novels.:\n")
data

Details of Highest selling novels.:

,Book,Book_ Author,Volumes_Sold,Publisher,Genre
Rank,,,,,
1,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
2,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
3,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
4,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
5,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
96,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
97,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
98,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
99,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
100,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

### Q9.Scrape the details most watched tv series of all time from imdb.com. Url = https://www.imdb.com/list/ls095964455/ You have to find the following details: A) Name B) Year span C) Genre D) Run time E) Ratings F) Votes

In [57]:
#First connect to the driver

driver= webdriver.Chrome(r"C:\Users\user\Downloads\chromedriver_win32\chromedriver.exe")

#open the page in automated chrome browser

driver.get(" https://www.imdb.com/list/ls095964455/")
time.sleep(2)

In [62]:
# Creating Empty List for scrapped data

name =[]
year=[]
genre =[]
run_time =[]
ratings =[]
votes =[]

In [63]:
# Scraping Name 
try:
    name_tags =driver.find_elements(By.XPATH,"//h3[@class='lister-item-header']/a")
    for i in name_tags:
        name.append(i.text)
except NoSuchElementException:
    name.append('NA')
    
# Scraping Year span
try:
    year_tags =driver.find_elements(By.XPATH,"//h3[@class='lister-item-header']/span[2]")
    for i in year_tags :
        year.append(i.text)
except NoSuchElementException:
    year.append('NA')
    
# Scraping Genre via Xpath
try:
    genre_tags =driver.find_elements(By.XPATH,"//span[@class='genre']")
    for i in genre_tags :
        genre.append(i.text)
except NoSuchElementException:
    genre.append('NA')
    
# Scraping Run Time 
try:
    run_time_tags =driver.find_elements(By.XPATH,"//span[@class='runtime']")
    for i in run_time_tags :
        run_time.append(i.text)
except NoSuchElementException:
    run_time.append('NA')
    
# Scraping Ratings
try:
    ratings_tags =driver.find_elements(By.XPATH,"//div[@class='ipl-rating-star small']/span[2]")
    for i in ratings_tags :
        ratings.append(i.text)
except NoSuchElementException:
    ratings.append('NA')

# Scraping Votes
try:
    votes_tags =driver.find_elements(By.XPATH,"//span[@name='nv']")
    for i in votes_tags :
        votes.append(i.text)
except NoSuchElementException:
    votes.append('NA')

In [67]:
print(len(name))
print(len(genre))
print(len(year))
print(len(run_time))
print(len(ratings))
print(len(votes))

100
100
100
100
100
100

In [68]:
# Creating DataFrame for scrapped data

data_list= list(zip(name,year,genre,run_time,ratings,votes ))

data= pd.DataFrame(data_list, 
    columns =['Name','Year span','Genre', 'Run_Time','Ratings','Votes'],
                  index=pd.RangeIndex(start=1, stop=101, name='Rank'))

#Print the required data

print ("Details of most watched tv series of all time from imdb.com. :\n")
data

Details of most watched tv series of all time from imdb.com. :

,Name,Year span,Genre,Run_Time,Ratings,Votes
Rank,,,,,,
1,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"2,060,361"
2,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"1,154,157"
3,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.1,"971,884"
4,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"289,813"
5,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"249,254"
...,...,...,...,...,...,...
96,Reign,(2013–2017),Drama,42 min,7.4,"49,680"
97,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"60,726"
98,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"195,452"
99,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"41,136"
100,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"237,993"

### Q10. Details of Datasets from UCI machine learning repositories.
Url = https://archive.ics.uci.edu/
You have to find the following details:
A) Dataset name
B) Data type
C) Task
D) Attribute type
E) No of instances
F) No of attribute
G) Year
Note: - from the home page you have to go to the ShowAllDataset page through code

In [69]:
#First connect to the driver

driver= webdriver.Chrome(r"C:\Users\user\Downloads\chromedriver_win32\chromedriver.exe")

#open the page in automated chrome browser

driver.get(" https://archive.ics.uci.edu/ ")
time.sleep(2)

In [70]:
# Clicking on all datasets links
dataset=driver.find_element(By.XPATH,"//a[@href='datasets.php']")
dataset.click()
time.sleep(1)

In [73]:
# Creating empty lists for scrapped data

name =[]
dtype =[]
task =[]
attribute_type =[]
no_of_instances =[]
no_of_Attri=[]
year=[]

In [74]:
# Scraping DataSet Name

try:
    name_tags =driver.find_elements(By.XPATH,"//p[@class='normal']/b/a")
    for i in name_tags:
        name.append(i.text)
except NoSuchElementException:
    name.append('NA')

In [77]:
# Scraping Data Type
try:
    dtype_tags=driver.find_elements(By.XPATH,'/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]')
    for i in dtype_tags[1:]:
        dtype.append(i.text)
except NoSuchElementException:
    dtype.append('NA')
    
# Scraping Task
try:
    task_tags =driver.find_elements(By.XPATH,'/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]')
    for i in task_tags [1:]:
        task.append(i.text)
except NoSuchElementException:
    task.append('NA')
    
# Scraping Attribute_Type
try:
    attribute_type_tags =driver.find_elements(By.XPATH,'/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]')
    for i in attribute_type_tags[1:]:
        attribute_type.append(i.text)
except NoSuchElementException:
    attribute_type.append('NA')
    
# Scraping No_of_Instances
try:
    no_of_instances_tags =driver.find_elements(By.XPATH,'/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]')
    for i in no_of_instances_tags [1:]:
        no_of_instances.append(i.text)
except NoSuchElementException:
    no_of_instances.append('NA')

# Scraping No_of_Attribute
try:
    no_of_Attri_tags =driver.find_elements(By.XPATH,'/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]')
    for i in no_of_Attri_tags [1:]:
        no_of_Attri.append(i.text)
except NoSuchElementException:
    no_of_Attri.append('NA')
    
# Scraping Year
try:
    year_tags =driver.find_elements(By.XPATH,'/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]')
    for i in year_tags[1:]:
        year.append(i.text)
except NoSuchElementException:
    year.append('NA')

In [80]:
print(len(name))
print(len(dtype))
print(len(task))
print(len(attribute_type))
print(len(no_of_instances))
print(len(no_of_Attri))
print(len(year))

622
622
622
622
622
622
622

In [81]:
# Creating DataFrame for scrapped data

data_list= list(zip(name,dtype,task,attribute_type,no_of_instances,no_of_Attri,year))

data= pd.DataFrame(data_list, 
    columns =['Name','Data Type','Task', 'Attribute_Type','No_of_Instances','No_of_Attribute','Year'],
                  index=pd.RangeIndex(start=1, stop=623, name='Sr No'))

#Print the required data

print ("Details of Datasets from UCI machine learning repositories :\n")
data

Details of Datasets from UCI machine learning repositories :

,Name,Data Type,Task,Attribute_Type,No_of_Instances,No_of_Attribute,Year
Sr No,,,,,,,
1,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
2,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
3,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
4,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
5,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
618,Influenza outbreak event prediction via Twitte...,Multivariate,Classification,"Integer, Real",75840,525,2020
619,Turkish Music Emotion Dataset,Multivariate,Classification,"Integer, Real",400,50,2020
620,Maternal Health Risk Data Set,,Classification,,1014,7,2020
621,Room Occupancy Estimation,"Multivariate, Time-Series",Classification,Real,10129,16,2021
622,Image Recognition Task Execution Times in Mobi...,Univariate,Regression,Real,4000,2,2021